### ISSUE TITLE
[Feature] Installation script for various libraries and software

### ISSUE THREAD

**Issue by kadensu** [Open-Acidification/AlkalinityTitrator#1]
Currently, to install and setup the raspberry pi with the needed software and libraries is a lengthy project. This could be made much quicker with an installation script.

**Comment by prestoncarman** [comment]
@all-contributors please add @kadensu for code, doc and bug

**Comment by TaylorSmith28** [comment]
This is implemented with the pip file. Unused dependencies have been removed as of #75
