### ISSUE TITLE
Refactor to allow for mocking the LCD

### ISSUE THREAD

**Issue by prestoncarman** [Open-Acidification/AlkalinityTitrator#14]

**Comment by KonradMcClure** [comment]
LCD_mock has been created to start to allow for simulation of the device without running of of it. The test mode can be accessed from adding the command line argument `-test`:
`python titration/titration.py -test`

This will set the `IS_TEST` flag in constants.py to True. When interfaces.setup_interfaces() is run, `setup_lcd()`is called, which checks the status of `IS_TEST`. The global variable `ui_lcd` is set to either the real class or mock class depending on whether IS_TEST is false or true respectively.

The LCD and LCD_mock classes have been made to closer match the function and nomenclature of Arduino's LiquidCrystal library to make them more general. The test_LCD class prints to the console with a border around the dimensions of the LCD as specified when calling LCD.begin(rows, cols):
```
*====================*
|1. Run titration    |
|2. Calibrate sensors|
|3. Prime Pump       |
|*. Page 2           |
*====================*
```
