### ISSUE TITLE
Refactor to allow for mocking the Keypad

### ISSUE THREAD

**Issue by prestoncarman** [Open-Acidification/AlkalinityTitrator#15]

**Comment by KonradMcClure** [comment]
Keypad_mock has been created to start to allow for simulation of the device without running of of it. The test mode can be accessed from adding the command line argument `-test`:
`python titration/titration.py -test`
This will set the `IS_TEST` flag in constants.py to True. When interfaces.setup_interfaces() is run, `setup_keypad()` is called, which checks the status of `IS_TEST`. `ui_keypad` with be set to either the real class or mock class depending on whether IS_TEST is false or true respectively.

The mock class simply uses `input()` for getting input from the user. Any input that's not on the keypad will simply be ignored, making only 0-9 and A-D valid (case sensitive right now). The way input is currently handled is through two calls to `ui_keypad.keypad_poll()` in the `interfaces.read_user_input()` function. This is to detect both when the user presses a button and then releases the button  before accepting the input. To handle that for the mock, every other time the mock `keypad_poll()` is called, it will return `None`, which is what the real `keypad_poll()` returns when no buttons are pressed.
