### ISSUE TITLE
Refactor to allow for mocking the Arduino connection

### ISSUE THREAD

**Issue by prestoncarman** [Open-Acidification/AlkalinityTitrator#17]

**Comment by KonradMcClure** [comment]
The Arduino controls the syringe pump. We need to be able to mock that connection to the Arduino so we can a test version of the program. Currently, the program will crash when it reaches the initialization (in interfaces.py) or a line that interacts with the arduino (interfaces.pump_volume())

By mocking the Serial class with serial_mock.py, the arduino can be swapped out with the mock connection. It'll always return the b"DONE\r\n" string when called with readline()
