### ISSUE TITLE
Reimplement partially-mocked mode

### ISSUE THREAD

**Issue by KonradMcClure** [Open-Acidification/AlkalinityTitrator#28]
Originally `IS_TEST` was created to create mock output/readings from the temp probe, pH probe, and arduino, but would still print to the LCD and take input from the keypad. Now that `IS_TEST` is being used for the full-mocked mode for running on non-Raspberry Pi devices, the test mode on the actual titrator won't display on the LCD.

At some point, the mocked mode needs to be refactored to check what devices it can interface with and which it can't. If it can talk to the LCD and keypad, but not any of the other instruments, it should still display on those.

**Comment by TaylorSmith28** [comment]
This has been implemented with #98 and #88, #89, #97
