### ISSUE TITLE
[Feature] Automated Testing

### ISSUE THREAD

**Issue by prestoncarman** [Open-Acidification/AlkalinityTitrator#4]
**Is your feature request related to a problem? Please describe.**
Each commit should test the system and confirm its working.

**Describe the solution you'd like**
A github action should be set up to run the automated tests.

**Comment by prestoncarman** [comment]
@all-contributors please add @prestoncarman for code and bug

**Comment by KonradMcClure** [comment]
Thanks to @prestoncarman this feature has been added to the github, and now we have a set of tests for the mock components to start with. As long as the paths are done correctly in those test files they'll run in the `pipenv` for commits and PRs. Closing this issue
