### ISSUE TITLE
Disabled isort from super-linter

### ISSUE THREAD

**Issue by KonradMcClure** [Open-Acidification/AlkalinityTitrator#41]
The `isort`  linter was misbehaving in the GitHub actions. On my device (Windows) I can run `isort` with the same config file as the super-linter and it will end without any errors or corrections. However, the super-linter's `isort` has a different idea of how things should be arranged so it threw errors.

For the time being we disabled `isort` until we figure out what was happening

**Comment by TaylorSmith28** [comment]
Isort has been enable #95
