### ISSUE TITLE
Old Files Need Removing

### ISSUE THREAD

**Issue by kieransukachevin** [Open-Acidification/AlkalinityTitrator#58]
Once the old files for the processes (interfaces.py, routines.py, analysis.py) have been integrated into the new UI State Machine, these files and the files specified as “old” (including the run_old.sh and run_old_mocked.sh scripts) can be removed in favor of the new UI State Machine version. Additionally,  the Readme instructions for running the “old” way should be removed once the new UI State Machine has been fully integrated.

**Comment by TaylorSmith28** [comment]
Fixed with #90
